### ISSUE TITLE
No Fedora 41 builds

### ISSUE THREAD

**Issue by dibenzepin** [somesi/linux-wifi-hotspot#3]
Just like the title says, there's no F41 builds. I updated from 40 → 41 and now dnf complains about the non-existence of `https://download.copr.fedorainfracloud.org/results/zinix01/linux-wifi-hotspot/fedora-41-x86_64/repodata/repomd.xml`

**Comment by somesi** [comment]
Sorry had some issues testing it on Fedora 41. Builds should be up now.
